# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log_ident', models.CharField(max_length=150)),
                ('compName', models.CharField(max_length=100)),
                ('msg', models.TextField(max_length=200)),
                ('dateTime', models.DateTimeField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='log.Category')),
            ],
        ),
    ]
